Traceback (most recent call last):
  File "/home/runner/micromamba/envs/coastal/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/micromamba/envs/coastal/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/coastal/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/coastal/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/coastal/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/runner/micromamba/envs/coastal/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/micromamba/envs/coastal/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Before running, install 'uptide' in the coastal environment as 'pip install uptide'
# Run this to import modules

import pathlib
from pathlib import Path
import sys
from warnings import filterwarnings
import ipywidgets as widgets
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import xarray as xr
from datetime import datetime, timedelta
from IPython.display import display, Image
import math
from ipywidgets import interact
import pooch
import uptide
import pickle

from initialize.Tide_Initialize import plot_timeseries_with_interactive_controls, questions_2d

cwd = pathlib.Path().resolve()
proj_dir = cwd.parent  # this is the root of the CoastalCodeBook
DATA_DIR = proj_dir / "data"

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 21[0m
[1;32m     19[0m [38;5;28;01mfrom[39;00m [38;5;21;01mipywidgets[39;00m [38;5;28;01mimport[39;00m interact
[1;32m     20[0m [38;5;28;01mimport[39;00m [38;5;21;01mpooch[39;00m
[0;32m---> 21[0m [38;5;28;01mimport[39;00m [38;5;21;01muptide[39;00m
[1;32m     22[0m [38;5;28;01mimport[39;00m [38;5;21;01mpickle[39;00m
[1;32m     24[0m [38;5;28;01mfrom[39;00m [38;5;21;01minitialize[39;00m[38;5;21;01m.[39;00m[38;5;21;01mTide_Initialize[39;00m [38;5;28;01mimport[39;00m plot_timeseries_with_interactive_controls, questions_2d

[0;31mModuleNotFoundError[0m: No module named 'uptide'

