Traceback (most recent call last):
  File "/Users/calkoen/mambaforge/envs/codebook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/calkoen/mambaforge/envs/codebook/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/calkoen/mambaforge/envs/codebook/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/calkoen/mambaforge/envs/codebook/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/calkoen/mambaforge/envs/codebook/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/calkoen/mambaforge/envs/codebook/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/calkoen/mambaforge/envs/codebook/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/calkoen/mambaforge/envs/codebook/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ans0 = 'N'  # Example answer

ans1 = 'A'  # Your answer for point 1
ans2 = 'C'  # Your answer for point 2
ans3 = 'D'  # Your answer for point 3
ans4 = 'D'  # Your answer for point 4
ans5 = 'D'  # Your answer for point 5

Check1(ans1,ans2,ans3,ans4,ans5) # Example function to run to validate answers
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[7], line 9[0m
[1;32m      6[0m ans4 [38;5;241m=[39m [38;5;124m'[39m[38;5;124mD[39m[38;5;124m'[39m  [38;5;66;03m# Your answer for point 4[39;00m
[1;32m      7[0m ans5 [38;5;241m=[39m [38;5;124m'[39m[38;5;124mD[39m[38;5;124m'[39m  [38;5;66;03m# Your answer for point 5[39;00m
[0;32m----> 9[0m [43mCheck1[49m(ans1,ans2,ans3,ans4,ans5) [38;5;66;03m# Example function to run to validate answers[39;00m

[0;31mNameError[0m: name 'Check1' is not defined
NameError: name 'Check1' is not defined

